version: 2.1

jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: alpine:latest
    resource_class: "xlarge"
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World! How are you?"
      - run:
          name: "Installing stress binary"
          command: apk add stress
      - run:
          name: "Running a stess load"
          command: stress -c 2 --vm 4 --vm-bytes 128M --timeout 1m &          
      - run:
          name: "Get the Host/OS details"
          command: "[ -f /etc/os-release ] && cat /etc/os-release"
      - run:
          name: "Print Hostname"
          command: "hash hostname && hostname"
      - run:
          name: "Entrypoint"
          command: "cat /proc/1/cmdline"
      - run:
          name: "I am calling from"
          command: "wget ipinfo.io && cat index.html && rm index.html || echo 'I am not going to work in Proxy Env'"          
      - run:
          name: "Get the running processes"
          command: "ps -ef"
      - run:
          name: "Bye"
          command: echo "Bye Bye $(date)"

workflows:
  nomad-docker:
    jobs:
      - say-hello
