version: 2.1

workflows:
  runner-jobs:
    jobs:
      - machine-runner

jobs:
  machine-runner:
    machine: true
    resource_class: atulsingh0/mrunner
    steps:
      - run: echo "Hi I'm on Machine Runners!"
      - run: sleep 5
      - run: |
          date
          hostname
          circleci-runner --version
          systemctl status circleci-runner | less
          
      - run: env
      - run: cat /proc/cmdline
      - run: ps -ef
      - run: cat /proc/1/cmdline
      - run: sleep 5
